default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: booktrail_development

test:
  <<: *default
  database: booktrail_test

production:
  <<: *default
  database: booktrail_production
  username: booktrail
  password: <%= ENV['BOOKTRAIL_DATABASE_PASSWORD'] %>
